name: ublue akmods 40
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '5 14 * * *'  # 2pm-ish UTC everyday (timed against official fedora container pushes, and after 'config')
  workflow_dispatch:

jobs:
  ublue-40:
    name: "build ublue-os/akmods:*-40"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 40